// wwwroot/src-react-backup/components/layout/Toolbar.tsx
import { FilePlus, FolderOpen, Save, Undo2, Redo2, ZoomIn, ZoomOut, Maximize2 } from 'lucide-react'
import { useTranslation } from 'react-i18next'

/**
 * 工具栏组件，位于 MenuBar 下方。
 * 提供快捷操作按钮：新建、打开、保存、撤销、重做、缩放控制。
 */
export default function Toolbar() {
  const { t } = useTranslation()

  return (
    <div className="flex items-center h-full px-3 gap-1">
      {/* 文件操作 */}
      <div className="flex gap-0.5">
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('menu.newProject')}
        >
          <FilePlus size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('menu.openProject')}
        >
          <FolderOpen size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('menu.saveProject')}
        >
          <Save size={18} />
        </button>
      </div>

      {/* 分隔线 */}
      <div className="w-px h-[22px] bg-gray-600 mx-1.5" />

      {/* 撤销 / 重做 */}
      <div className="flex gap-0.5">
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 disabled:opacity-35 disabled:cursor-not-allowed transition-all duration-150"
          title={`${t('menu.undo')} (Ctrl+Z)`}
        >
          <Undo2 size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 disabled:opacity-35 disabled:cursor-not-allowed transition-all duration-150"
          title={`${t('menu.redo')} (Ctrl+Y)`}
        >
          <Redo2 size={18} />
        </button>
      </div>

      {/* 分隔线 */}
      <div className="w-px h-[22px] bg-gray-600 mx-1.5" />

      {/* 缩放控制 */}
      <div className="flex gap-0.5">
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('editor.zoomOut')}
        >
          <ZoomOut size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('editor.zoomIn')}
        >
          <ZoomIn size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('editor.fitView')}
        >
          <Maximize2 size={18} />
        </button>
      </div>
    </div>
  )
}

// wwwroot/src/components/layout/Toolbar.vue
<template>
  <div class="toolbar">
    <div class="toolbar-group">
      <button 
        class="toolbar-button" 
        :title="t('menu.new')"
        @click="handleNew"
      >
        <FilePlus :size="20" />
      </button>
      <button 
        class="toolbar-button" 
        :title="t('menu.open')"
        @click="handleOpen"
      >
        <FolderOpen :size="20" />
      </button>
      <button 
        class="toolbar-button" 
        :title="t('menu.save')"
        @click="handleSave"
      >
        <Save :size="20" />
      </button>
    </div>
    
    <div class="toolbar-divider"></div>
    
    <div class="toolbar-group">
      <button 
        class="toolbar-button" 
        :title="t('menu.undo')"
        @click="handleUndo"
      >
        <Undo :size="20" />
      </button>
      <button 
        class="toolbar-button" 
        :title="t('menu.redo')"
        @click="handleRedo"
      >
        <Redo :size="20" />
      </button>
    </div>
    
    <div class="toolbar-divider"></div>
    
    <div class="toolbar-group">
      <button 
        class="toolbar-button" 
        :title="t('menu.cut')"
        @click="handleCut"
      >
        <Scissors :size="20" />
      </button>
      <button 
        class="toolbar-button" 
        :title="t('menu.copy')"
        @click="handleCopy"
      >
        <Copy :size="20" />
      </button>
      <button 
        class="toolbar-button" 
        :title="t('menu.paste')"
        @click="handlePaste"
      >
        <Clipboard :size="20" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { FilePlus, FolderOpen, Save, Undo, Redo, Scissors, Copy, Clipboard } from 'lucide-vue-next'
import { useLocalization } from '@/composables/useLocalization'

const { t } = useLocalization()

function handleNew() {
  console.log('New file')
}

function handleOpen() {
  console.log('Open file')
}

function handleSave() {
  console.log('Save file')
}

function handleUndo() {
  console.log('Undo')
}

function handleRedo() {
  console.log('Redo')
}

function handleCut() {
  console.log('Cut')
}

function handleCopy() {
  console.log('Copy')
}

function handlePaste() {
  console.log('Paste')
}
</script>

<style scoped>
.toolbar {
  display: flex;
  align-items: center;
  height: 100%;
  padding: 0 12px;
  gap: 8px;
}

.toolbar-group {
  display: flex;
  gap: 4px;
}

.toolbar-button {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  background: transparent;
  border: none;
  border-radius: 4px;
  color: #cccccc;
  cursor: pointer;
}

.toolbar-button:hover {
  background: rgba(255, 255, 255, 0.1);
}

.toolbar-button:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.toolbar-divider {
  width: 1px;
  height: 24px;
  background: #3e3e42;
  margin: 0 8px;
}
</style>
