// wwwroot/src/components/layout/StatusBar.vue
<template>
  <div class="status-bar">
    <div class="status-left">
      <span v-if="editorStore.isModified" class="status-item modified">
        ● {{ t('common.modified') || 'Modified' }}
      </span>
      <span class="status-item">{{ statusMessage }}</span>
      <span v-if="editorStore.error" class="status-item error">
        ⚠ {{ editorStore.error }}
      </span>
    </div>
    <div class="status-right">
      <span class="status-item clickable" :title="t('settings.language')" @click="toggleLanguage">
        🌐 {{ currentLanguageLabel }}
      </span>
      <span class="status-item">{{ zoomLevel }}%</span>
      <span class="status-item" title="Node count">
        🔷 {{ nodeCount }} {{ t('common.nodes') || 'nodes' }}
      </span>
      <span v-if="connectionCount > 0" class="status-item" title="Connection count">
        🔗 {{ connectionCount }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useLocalization } from '@/composables/useLocalization'
import { useNodeGraphStore } from '@/stores/useNodeGraphStore'
import { useEditorStore } from '@/stores/useEditorStore'

const { t, currentLanguage, changeLanguage } = useLocalization()
const nodeGraphStore = useNodeGraphStore()
const editorStore = useEditorStore()

const statusMessage = computed(() => {
  if (editorStore.isLoading) return t('app.loading') || 'Loading...'
  if (editorStore.error) return ''
  return t('status.ready') || 'Ready'
})

const currentLanguageLabel = computed(() => {
  const lang = currentLanguage.value
  return lang.startsWith('zh') ? '中文' : lang.startsWith('ja') ? '日本語' : 'EN'
})

const zoomLevel = computed(() => 100)
const nodeCount = computed(() => nodeGraphStore.nodeCount)
const connectionCount = computed(() => nodeGraphStore.connectionCount)

async function toggleLanguage() {
  const current = currentLanguage.value
  const newLang = current.startsWith('zh') ? 'en-US' : 'zh-CN'
  await changeLanguage(newLang)
}
</script>

<style scoped>
.status-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 100%;
  padding: 0 16px;
  color: #ffffff;
  font-size: 12px;
  flex: 1;
}

.status-left,
.status-right {
  display: flex;
  align-items: center;
  gap: 20px;
}

.status-item {
  opacity: 0.9;
  white-space: nowrap;
}

.status-item.modified {
  color: #e8d4a8;
}

.status-item.error {
  color: #f48771;
}

.status-item.clickable {
  cursor: pointer;
  padding: 1px 6px;
  border-radius: 3px;
  transition: background 0.15s;
}

.status-item.clickable:hover {
  background: rgba(255, 255, 255, 0.15);
}
</style>

// wwwroot/src-react-backup/components/layout/StatusBar.tsx
import { useTranslation } from 'react-i18next'
import { useEditorStore } from '@/stores/useEditorStore'
import { useNodeGraphStore } from '@/stores/useNodeGraphStore'
import { useLocalization } from '@/hooks/useLocalization'

/**
 * 底部状态栏组件。
 * 左侧显示当前编辑文件路径（含修改标记），
 * 右侧显示语言切换、缩放比例、节点数量。
 */
export default function StatusBar() {
  const { t } = useTranslation()
  const { currentLanguage, changeLanguage } = useLocalization()
  const currentFile = useEditorStore((s) => s.currentFile)
  const isDirty = useEditorStore((s) => s.isDirty)
  const nodeCount = useNodeGraphStore((s) => s.nodes.length)
  const viewportZoom = useNodeGraphStore((s) => s.viewportZoom)

  const languageLabel = currentLanguage === 'zh' ? '中文' : 'EN'

  return (
    <div className="flex items-center justify-between h-full px-4 text-white text-xs flex-1">
      {/* 左侧：当前文件路径 */}
      <div className="flex items-center gap-5">
        {isDirty && (
          <span className="text-amber-300 opacity-90 whitespace-nowrap">
            ● {t('app.modified', '已修改')}
          </span>
        )}
        <span className="opacity-90 whitespace-nowrap">{currentFile || 'Untitled'}</span>
      </div>

      {/* 右侧：语言切换、缩放、节点数 */}
      <div className="flex items-center gap-5">
        <button
          className="opacity-90 cursor-pointer hover:bg-white/15 rounded px-1.5 py-0.5 transition-colors duration-150 whitespace-nowrap"
          title={t('settings.language')}
          onClick={() => changeLanguage(currentLanguage === 'zh' ? 'en' : 'zh')}
        >
          🌐 {languageLabel}
        </button>
        <span className="opacity-90 whitespace-nowrap">{Math.round(viewportZoom * 100)}%</span>
        <span className="opacity-90 whitespace-nowrap" title="Node count">
          🔷 {nodeCount} {t('common.nodes', 'nodes')}
        </span>
      </div>
    </div>
  )
}
