// visunovia.client/src/components/layout/Toolbar.vue
<template>
  <div class="toolbar">
    <div class="toolbar-group">
      <button
        class="toolbar-button"
        :title="t('panels.project')"
        @click="uiStore.openProjectPopup()"
      >
        <FolderOpen :size="18" />
      </button>
      <button
        class="toolbar-button"
        title="刷新项目资源"
        @click="handleRefreshProjectTree"
      >
        <RefreshCw :size="18" />
      </button>
      <button
        class="toolbar-button"
        title="角色管理器"
        @click="uiStore.openCharacterManager()"
      >
        <Users :size="18" />
      </button>
      <button
        class="toolbar-button"
        :title="t('menu.new')"
        @click="handleNew"
      >
        <FilePlus :size="18" />
      </button>
      <button
        class="toolbar-button"
        :title="t('menu.save')"
        @click="handleSave"
      >
        <Save :size="18" />
      </button>
    </div>

    <div class="toolbar-divider"></div>

    <div class="toolbar-group">
      <button
        class="toolbar-button"
        :title="`${t('menu.undo')} (${undoDescription || 'Ctrl+Z'})`"
        :disabled="!undoRedoStore.canUndo"
        @click="handleUndo"
      >
        <Undo2 :size="18" />
      </button>
      <button
        class="toolbar-button"
        :title="`${t('menu.redo')} (${redoDescription || 'Ctrl+Y'})`"
        :disabled="!undoRedoStore.canRedo"
        @click="handleRedo"
      >
        <Redo2 :size="18" />
      </button>
    </div>

    <!-- Spacer -->
    <div class="toolbar-spacer"></div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { FilePlus, FolderOpen, RefreshCw, Save, Undo2, Redo2, Users } from 'lucide-vue-next'
import { useLocalization } from '@/composables/useLocalization'
import { useUIStore } from '@/stores/useUIStore'
import { useEditorStore } from '@/stores/useEditorStore'
import { useUndoRedoStore } from '@/stores/useUndoRedoStore'
import { useNodeGraphStore } from '@/stores/useNodeGraphStore'

const { t } = useLocalization()
const uiStore = useUIStore()
const editorStore = useEditorStore()
const undoRedoStore = useUndoRedoStore()
const nodeGraphStore = useNodeGraphStore()

const undoDescription = computed(() => undoRedoStore.getUndoDescription())
const redoDescription = computed(() => undoRedoStore.getRedoDescription())

function handleNew() {
  uiStore.openNewProjectModal()
}

function handleSave() {
  editorStore.save()
}

function handleRefreshProjectTree() {
  uiStore.openProjectPopup()
  uiStore.refreshProjectTree()
}

function handleUndo() {
  const state = undoRedoStore.undo()
  if (state) {
    nodeGraphStore.deserializeGraph({
      nodes: state.nodes,
      connections: state.connections
    })
  }
}

function handleRedo() {
  const state = undoRedoStore.redo()
  if (state) {
    nodeGraphStore.deserializeGraph({
      nodes: state.nodes,
      connections: state.connections
    })
  }
}
</script>

<style scoped>
.toolbar {
  display: flex;
  align-items: center;
  height: 100%;
  padding: 0 12px;
  gap: 4px;
}

.toolbar-group {
  display: flex;
  gap: 2px;
}

.toolbar-button {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  background: transparent;
  border: none;
  border-radius: 4px;
  color: #cccccc;
  cursor: pointer;
  transition: all 0.15s;
}

.toolbar-button:hover:not(:disabled) {
  background: rgba(255, 255, 255, 0.1);
  color: #ffffff;
}

.toolbar-button:active:not(:disabled) {
  background: rgba(255, 255, 255, 0.15);
  transform: scale(0.96);
}

.toolbar-button:disabled {
  opacity: 0.35;
  cursor: not-allowed;
}

.toolbar-divider {
  width: 1px;
  height: 22px;
  background: #3e3e42;
  margin: 0 6px;
}

.toolbar-spacer {
  flex: 1;
}
</style>

// wwwroot/src-react-backup/components/layout/Toolbar.tsx
import { FilePlus, FolderOpen, Save, Undo2, Redo2, ZoomIn, ZoomOut, Maximize2 } from 'lucide-react'
import { useTranslation } from 'react-i18next'

/**
 * 工具栏组件，位于 MenuBar 下方。
 * 提供快捷操作按钮：新建、打开、保存、撤销、重做、缩放控制。
 */
export default function Toolbar() {
  const { t } = useTranslation()

  return (
    <div className="flex items-center h-full px-3 gap-1">
      {/* 文件操作 */}
      <div className="flex gap-0.5">
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('menu.newProject')}
        >
          <FilePlus size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('menu.openProject')}
        >
          <FolderOpen size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('menu.saveProject')}
        >
          <Save size={18} />
        </button>
      </div>

      {/* 分隔线 */}
      <div className="w-px h-[22px] bg-gray-600 mx-1.5" />

      {/* 撤销 / 重做 */}
      <div className="flex gap-0.5">
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 disabled:opacity-35 disabled:cursor-not-allowed transition-all duration-150"
          title={`${t('menu.undo')} (Ctrl+Z)`}
        >
          <Undo2 size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 disabled:opacity-35 disabled:cursor-not-allowed transition-all duration-150"
          title={`${t('menu.redo')} (Ctrl+Y)`}
        >
          <Redo2 size={18} />
        </button>
      </div>

      {/* 分隔线 */}
      <div className="w-px h-[22px] bg-gray-600 mx-1.5" />

      {/* 缩放控制 */}
      <div className="flex gap-0.5">
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('editor.zoomOut')}
        >
          <ZoomOut size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('editor.zoomIn')}
        >
          <ZoomIn size={18} />
        </button>
        <button
          className="flex items-center justify-center w-8 h-8 bg-transparent border-none rounded text-gray-300 hover:bg-white/10 hover:text-white active:bg-white/15 active:scale-95 transition-all duration-150"
          title={t('editor.fitView')}
        >
          <Maximize2 size={18} />
        </button>
      </div>
    </div>
  )
}
