// wwwroot/src-react-backup/components/dialogs/WindowPopup.tsx
import { type ReactNode } from 'react'
import { X } from 'lucide-react'

interface WindowPopupProps {
  /** 弹窗标题 */
  title: string
  /** 子内容 */
  children: ReactNode
  /** 关闭回调 */
  onClose: () => void
  /** 确认回调 */
  onConfirm?: () => void
  /** 取消回调 */
  onCancel?: () => void
  /** 确认按钮文本 */
  confirmLabel?: string
  /** 取消按钮文本 */
  cancelLabel?: string
  /** 宽度 */
  width?: string
  /** 高度 */
  height?: string
  /** 是否显示底部按钮栏 */
  showFooter?: boolean
}

export default function WindowPopup({
  title,
  children,
  onClose,
  onConfirm,
  onCancel,
  confirmLabel = '确认',
  cancelLabel = '取消',
  width,
  height,
  showFooter = true,
}: WindowPopupProps) {
  const handleClose = () => {
    if (onCancel) {
      onCancel()
    } else {
      onClose()
    }
  }

  return (
    <div
      className="flex flex-col bg-gray-900 text-gray-100 overflow-hidden"
      style={{ width, height: height || '100vh' }}
    >
      {/* 标题栏 */}
      <header className="flex items-center justify-between px-6 py-3 bg-gray-800/50 border-b border-gray-700 shrink-0">
        <h1 className="text-lg font-semibold text-gray-100">{title}</h1>
        <button
          className="p-1 text-gray-400 hover:text-gray-200 rounded transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500/50"
          onClick={handleClose}
          aria-label="关闭"
        >
          <X size={18} />
        </button>
      </header>

      {/* 内容区域 */}
      <main className="flex-1 p-6 overflow-y-auto">{children}</main>

      {/* 底部按钮栏 */}
      {showFooter && (onConfirm || onCancel) && (
        <footer className="flex items-center justify-end gap-3 px-6 py-3 bg-gray-800/50 border-t border-gray-700 shrink-0">
          {onCancel && (
            <button
              className="px-4 py-2 text-sm font-medium text-gray-300 bg-gray-700 rounded hover:bg-gray-600 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500/50"
              onClick={onCancel}
            >
              {cancelLabel}
            </button>
          )}
          {onConfirm && (
            <button
              className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded hover:bg-blue-500 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500/50"
              onClick={onConfirm}
            >
              {confirmLabel}
            </button>
          )}
        </footer>
      )}
    </div>
  )
}

// wwwroot/src/components/dialogs/WindowPopup.vue
<template>
  <div
    class="window-popup"
    :style="{ width: width, height: height }"
  >
    <!-- 标题栏 -->
    <header class="window-popup-header">
      <h1 class="window-popup-title">{{ title }}</h1>
      <button
        class="window-popup-close-button"
        @click="handleClose"
        aria-label="关闭"
      >
        <X :size="18" />
      </button>
    </header>

    <!-- 内容区域 -->
    <main class="window-popup-content">
      <slot></slot>
    </main>

    <!-- 底部按钮栏 -->
    <footer
      v-if="showFooter && (onConfirm || onCancel)"
      class="window-popup-footer"
    >
      <button
        v-if="onCancel"
        class="cancel-button"
        @click="onCancel"
      >
        {{ cancelLabel }}
      </button>
      <button
        v-if="onConfirm"
        class="confirm-button"
        @click="onConfirm"
      >
        {{ confirmLabel }}
      </button>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { X } from 'lucide-vue-next'

interface Props {
  title: string
  onConfirm?: () => void
  onCancel?: () => void
  confirmLabel?: string
  cancelLabel?: string
  width?: string
  height?: string
  showFooter?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  confirmLabel: '确认',
  cancelLabel: '取消',
  showFooter: true
})

const handleClose = () => {
  if (props.onCancel) {
    props.onCancel()
  }
}
</script>

<style scoped>
.window-popup {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background-color: #111827;
  color: #f3f4f6;
  overflow: hidden;
}

.window-popup-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 24px;
  background-color: rgba(31, 41, 55, 0.5);
  border-bottom: 1px solid #374151;
  flex-shrink: 0;
}

.window-popup-title {
  font-size: 18px;
  font-weight: 600;
  color: #f3f4f6;
}

.window-popup-close-button {
  padding: 4px;
  color: #9ca3af;
  background: transparent;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: color 0.2s;
}

.window-popup-close-button:hover {
  color: #e5e7eb;
}

.window-popup-close-button:focus {
  outline: none;
  box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.5);
}

.window-popup-content {
  flex: 1;
  padding: 24px;
  overflow-y: auto;
}

.window-popup-footer {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 12px;
  padding: 12px 24px;
  background-color: rgba(31, 41, 55, 0.5);
  border-top: 1px solid #374151;
  flex-shrink: 0;
}

.cancel-button,
.confirm-button {
  padding: 8px 16px;
  font-size: 14px;
  font-weight: 500;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.2s;
}

.cancel-button {
  color: #d1d5db;
  background-color: #374151;
}

.cancel-button:hover {
  background-color: #4b5563;
}

.confirm-button {
  color: #ffffff;
  background-color: #2563eb;
}

.confirm-button:hover {
  background-color: #3b82f6;
}

.cancel-button:focus,
.confirm-button:focus {
  outline: none;
  box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.5);
}
</style>
