// wwwroot/src/components/modals/ResourcePickerModal.vue
<template>
  <Teleport to="body">
    <div v-if="visible" class="modal-overlay" @click.self="handleCancel">
      <div class="resource-picker-modal">
        <!-- 标题栏 -->
        <div class="modal-header">
          <span class="modal-title">{{ modalTitle }}</span>
          <button class="modal-close-btn" @click="handleCancel">✕</button>
        </div>

        <!-- 文件网格 -->
        <div class="modal-body">
          <div v-if="filteredFiles.length === 0" class="empty-hint">
            {{ t('resource.noFiles', '无匹配的资源文件') }}
          </div>
          <div v-else class="file-grid">
            <div
              v-for="file in filteredFiles"
              :key="file.path"
              :class="['file-item', { selected: isSelected(file.path) }]"
              @click="handleSelect(file.path)"
              @dblclick="handleConfirm(file.path)"
            >
              <!-- 图片预览或文件图标 -->
              <img
                v-if="isImageType && file.thumbnail"
                :src="file.thumbnail"
                :alt="file.name"
                class="file-thumbnail"
                loading="lazy"
              />
              <div v-else :class="['file-icon', `icon-${file.ext.slice(1)}`]">
                {{ getFileIconLetter(file.ext) }}
              </div>
              <span class="file-name" :title="file.name">{{ file.name }}</span>
            </div>
          </div>
        </div>

        <!-- 底部按钮 -->
        <div class="modal-footer">
          <button class="btn btn-cancel" @click="handleCancel">
            {{ t('common.cancel', '取消') }}
          </button>
          <button
            class="btn btn-confirm"
            :disabled="!selectedPath"
            @click="handleConfirm(selectedPath)"
          >
            {{ t('common.ok', '确认') }}
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { RESOURCE_TYPE_EXTENSIONS, type ResourceType } from '@/stores/useResourceRegistry'

const props = defineProps<{
  visible: boolean
  resourceType: ResourceType
  currentPath?: string
  /** 工作区文件列表（由父组件传入） */
  files?: Array<{ name: string; path?: string }>
}>()

const emit = defineEmits<{
  confirm: [path: string]
  cancel: []
}>()

const { t } = useI18n()
const selectedPath = ref('')

/** 图片类型的资源类型集合 */
const IMAGE_TYPES: ResourceType[] = ['image']

const isImageType = computed(() => IMAGE_TYPES.includes(props.resourceType))

/** 模态框标题 */
const modalTitle = computed(() => {
  const titles: Record<ResourceType, string> = {
    image: t('resource.selectImage', '选择图片资源'),
    audio: t('resource.selectAudio', '选择音效资源'),
    bgm:   t('resource.selectBgm', '选择背景音乐'),
    voice: t('resource.selectVoice', '选择语音资源'),
    video: t('resource.selectVideo', '选择视频资源'),
    scene: t('resource.selectScene', '选择场景资源'),
    font:  t('resource.selectFont', '选择字体资源'),
    data:  t('resource.selectData', '选择数据资源'),
  }
  return titles[props.resourceType] || t('resource.selectResource', '选择资源')
})

/** 过滤后的文件列表 */
const filteredFiles = computed(() => {
  const allFiles = props.files || []
  const exts = RESOURCE_TYPE_EXTENSIONS[props.resourceType] || []
  return allFiles
    .filter((f: any) => {
      const ext = f.name?.slice(f.name.lastIndexOf('.')).toLowerCase() || ''
      return exts.includes(ext)
    })
    .map((f: any) => ({
      name: f.name,
      path: f.path || f.name,
      ext: f.name?.slice(f.name.lastIndexOf('.')).toLowerCase() || '',
      thumbnail: f.path ? `/assets/${encodeURIComponent(f.path)}` : '',
    }))
})

function isSelected(path: string): boolean {
  return selectedPath.value === path
}

function handleSelect(path: string): void {
  selectedPath.value = selectedPath.value === path ? '' : path
}

function handleConfirm(path: string): void {
  emit('confirm', path)
  selectedPath.value = ''
}

function handleCancel(): void {
  emit('cancel')
  selectedPath.value = ''
}

function getFileIconLetter(ext: string): string {
  const map: Record<string, string> = {
    '.mp3': '♫', '.wav': '♪', '.ogg': '♬',
    '.mp4': '▶', '.webm': '▶',
    '.json': '{', '.xml': '<',
    '.ttf': 'A', '.otf': 'A', '.woff': 'A',
    '.txt': 'T',
  }
  return map[ext] || '?'
}

// 打开时重置选中状态
watch(() => props.visible, (val) => {
  if (val) {
    selectedPath.value = props.currentPath || ''
  }
})
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10000;
}
.resource-picker-modal {
  width: 640px;
  max-height: 70vh;
  background: #1e1e2e;
  border-radius: 12px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px;
  border-bottom: 1px solid #333346;
}
.modal-title {
  font-size: 15px;
  font-weight: 600;
  color: #e0e0e0;
}
.modal-close-btn {
  background: none;
  border: none;
  color: #888;
  font-size: 18px;
  cursor: pointer;
  padding: 4px 8px;
  border-radius: 4px;
}
.modal-close-btn:hover { color: #fff; background: rgba(255,255,255,0.1); }
.modal-body {
  padding: 16px;
  overflow-y: auto;
  min-height: 200px;
  max-height: 50vh;
}
.file-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(110px, 1fr));
  gap: 10px;
}
.file-item {
  border: 2px solid transparent;
  border-radius: 8px;
  padding: 8px;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  transition: all 0.15s ease;
  background: #2a2a3c;
}
.file-item:hover { border-color: #555; background: #333348; }
.file-item.selected { border-color: #7c3aed; background: rgba(124, 58, 237, 0.15); }
.file-thumbnail {
  width: 80px;
  height: 60px;
  object-fit: cover;
  border-radius: 4px;
  background: #111;
}
.file-icon {
  width: 80px;
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28px;
  border-radius: 4px;
  background: #222235;
  color: #888;
}
.file-name {
  font-size: 11px;
  color: #aaa;
  text-align: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  width: 100%;
}
.empty-hint {
  text-align: center;
  color: #666;
  padding: 40px 20px;
  font-size: 14px;
}
.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  padding: 14px 20px;
  border-top: 1px solid #333346;
}
.btn {
  padding: 8px 20px;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: none;
  transition: all 0.15s;
}
.btn-cancel { background: #333346; color: #ccc; }
.btn-cancel:hover { background: #444459; }
.btn-confirm { background: #7c3aed; color: #fff; }
.btn-confirm:hover:not(:disabled) { background: #6d28d9; }
.btn-confirm:disabled { opacity: 0.4; cursor: not-allowed; }
</style>

// wwwroot/src-react-backup/components/dialogs/ResourcePickerModal.tsx
import { useState, useEffect, useMemo } from 'react'
import type { LucideIcon } from 'lucide-react'
import { X, Search, Image, Music, Video } from 'lucide-react'
import { getEntries } from '@/api/fileBrowser'

/** 支持的资源类型 */
export type ResourceType = 'image' | 'audio' | 'video' | 'font' | 'data'

/** 各资源类型对应的文件扩展名集合 */
export const RESOURCE_TYPE_EXTENSIONS: Record<ResourceType, string[]> = {
  image: ['.png', '.jpg', '.jpeg', '.gif', '.bmp', '.svg', '.webp', '.ico'],
  audio: ['.mp3', '.wav', '.ogg', '.flac', '.aac', '.m4a', '.opus'],
  video: ['.mp4', '.webm', '.avi', '.mov', '.mkv'],
  font: ['.ttf', '.otf', '.woff', '.woff2'],
  data: ['.json', '.xml', '.csv', '.txt', '.yaml', '.yml'],
}

/** 资源类型选项卡定义 */
interface ResourceTab {
  type: ResourceType
  label: string
  icon: LucideIcon
}

const RESOURCE_TABS: ResourceTab[] = [
  { type: 'image', label: '图片', icon: Image },
  { type: 'audio', label: '音频', icon: Music },
  { type: 'video', label: '视频', icon: Video },
]

/** 文件条目（经处理后的展示用数据） */
interface FileEntry {
  name: string
  path: string
  ext: string
  thumbnail: string
  isSelected: boolean
}

interface ResourcePickerModalProps {
  /** 是否可见 */
  visible: boolean
  /** 资源类型（初始选中的选项卡） */
  resourceType: ResourceType
  /** 当前已选中的路径 */
  currentPath?: string
  /** 确认回调，传入选中路径 */
  onSelect: (path: string) => void
  /** 取消回调 */
  onCancel: () => void
}

/** 默认浏览目录 */
const DEFAULT_BROWSE_PATH = 'assets'

export default function ResourcePickerModal({
  visible,
  resourceType,
  currentPath,
  onSelect,
  onCancel,
}: ResourcePickerModalProps) {
  const [activeTab, setActiveTab] = useState<ResourceType>(resourceType)
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedPath, setSelectedPath] = useState(currentPath || '')
  const [files, setFiles] = useState<FileEntry[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  /** 图片类型集合 */
  const IMAGE_TYPES: ResourceType[] = ['image']

  /** 当前选项卡是否为图片类型 */
  const isImageType = IMAGE_TYPES.includes(activeTab)

  /** 打开时重置状态并加载文件 */
  useEffect(() => {
    if (!visible) return

    setActiveTab(resourceType)
    setSelectedPath(currentPath || '')
    setSearchQuery('')
    setError(null)
    loadFiles(resourceType)
  }, [visible, resourceType, currentPath])

  /** 加载文件列表 */
  const loadFiles = async (type: ResourceType) => {
    setIsLoading(true)
    setError(null)
    try {
      const data = await getEntries(DEFAULT_BROWSE_PATH)
      const exts = RESOURCE_TYPE_EXTENSIONS[type] || []
      const filtered = data.entries
        .filter((entry) => {
          if (entry.isDirectory) return false
          const ext = entry.name.slice(entry.name.lastIndexOf('.')).toLowerCase()
          return exts.includes(ext)
        })
        .map((entry) => ({
          name: entry.name,
          path: `${DEFAULT_BROWSE_PATH}/${entry.name}`,
          ext: entry.name.slice(entry.name.lastIndexOf('.')).toLowerCase(),
          thumbnail: isImageType
            ? `/assets/${encodeURIComponent(`${DEFAULT_BROWSE_PATH}/${entry.name}`)}`
            : '',
          isSelected: false,
        }))
      setFiles(
        filtered.map((f) => ({
          ...f,
          isSelected: f.path === (currentPath || ''),
        }))
      )
    } catch (err) {
      console.error('加载文件列表失败:', err)
      setError('无法加载资源文件列表，请检查文件浏览器 API 是否正常运行')
      setFiles([])
    } finally {
      setIsLoading(false)
    }
  }

  /** 切换选项卡时重新加载 */
  const handleTabChange = (tab: ResourceType) => {
    setActiveTab(tab)
    setSelectedPath('')
    setSearchQuery('')
    loadFiles(tab)
  }

  /** 过滤后的文件列表 */
  const filteredFiles = useMemo(() => {
    const query = searchQuery.trim().toLowerCase()
    if (!query) return files
    return files.filter((f) => f.name.toLowerCase().includes(query))
  }, [files, searchQuery])

  /** 获取文件图标字母 */
  const getFileIconLetter = (ext: string): string => {
    const map: Record<string, string> = {
      '.mp3': '♫',
      '.wav': '♪',
      '.ogg': '♬',
      '.flac': '♩',
      '.aac': '♫',
      '.mp4': '▶',
      '.webm': '▶',
      '.avi': '▶',
      '.mov': '▶',
      '.mkv': '▶',
      '.m4a': '♫',
      '.opus': '♫',
    }
    return map[ext] || '?'
  }

  /** 选择 / 取消选择文件 */
  const handleSelectFile = (path: string) => {
    setSelectedPath((prev) => (prev === path ? '' : path))
  }

  /** 确认选择 */
  const handleConfirm = () => {
    if (selectedPath) {
      onSelect(selectedPath)
    }
  }

  /** 取消并重置 */
  const handleCancel = () => {
    setSelectedPath('')
    setSearchQuery('')
    onCancel()
  }

  /** 点击遮罩层关闭 */
  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      handleCancel()
    }
  }

  /** 双击直接确认选择 */
  const handleDoubleClick = (path: string) => {
    setSelectedPath(path)
    onSelect(path)
  }

  if (!visible) return null

  return (
    <div
      className="fixed inset-0 bg-black/60 flex items-center justify-center z-[10000]"
      onClick={handleOverlayClick}
    >
      <div className="w-[600px] max-h-[70vh] bg-[#1e1e2e] rounded-xl shadow-2xl flex flex-col overflow-hidden">
        {/* 标题栏 */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#333346]">
          <span className="text-[15px] font-semibold text-gray-200">
            选择资源
          </span>
          <button
            className="bg-none border-none text-gray-500 hover:text-white hover:bg-white/10 rounded p-1 transition-colors"
            onClick={handleCancel}
          >
            <X size={18} />
          </button>
        </div>

        {/* 资源类型选项卡 */}
        <div className="flex border-b border-[#333346] px-5">
          {RESOURCE_TABS.map((tab) => {
            const Icon = tab.icon
            const isActive = activeTab === tab.type
            return (
              <button
                key={tab.type}
                className={`flex items-center gap-1.5 px-3 py-2 text-[13px] font-medium border-b-2 transition-colors ${
                  isActive
                    ? 'text-purple-400 border-purple-400'
                    : 'text-gray-500 border-transparent hover:text-gray-300'
                }`}
                onClick={() => handleTabChange(tab.type)}
              >
                <Icon size={14} />
                {tab.label}
              </button>
            )
          })}
        </div>

        {/* 搜索框 */}
        <div className="flex items-center gap-2 px-5 py-2.5">
          <Search size={14} className="text-gray-500 shrink-0" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="搜索资源文件..."
            className="flex-1 px-3 py-1.5 bg-[#2a2a3c] border border-[#444] rounded text-[13px] text-gray-200 outline-none placeholder:text-gray-500 focus:border-purple-500 transition-colors"
          />
          {searchQuery && (
            <button
              className="text-gray-500 hover:text-gray-300"
              onClick={() => setSearchQuery('')}
            >
              <X size={14} />
            </button>
          )}
        </div>

        {/* 文件列表 */}
        <div className="flex-1 px-4 py-4 overflow-y-auto min-h-[200px] max-h-[50vh]">
          {isLoading ? (
            <div className="flex items-center justify-center py-10 text-gray-500 text-sm">
              加载中...
            </div>
          ) : error ? (
            <div className="flex items-center justify-center py-10 text-red-400 text-sm">
              {error}
            </div>
          ) : filteredFiles.length === 0 ? (
            <div className="text-center text-gray-600 py-10 text-sm">
              无匹配的资源文件
            </div>
          ) : (
            <div className="grid gap-2.5 grid-cols-[repeat(auto-fill,minmax(110px,1fr))]">
              {filteredFiles.map((file) => (
                <div
                  key={file.path}
                  className={`flex flex-col items-center gap-1.5 p-2 rounded-lg border-2 cursor-pointer transition-all duration-150 bg-[#2a2a3c] ${
                    file.path === selectedPath
                      ? 'border-purple-500 bg-purple-500/15'
                      : 'border-transparent hover:border-gray-600 hover:bg-[#333348]'
                  }`}
                  onClick={() => handleSelectFile(file.path)}
                  onDoubleClick={() => handleDoubleClick(file.path)}
                >
                  {/* 缩略图或文件图标 */}
                  {isImageType && file.thumbnail ? (
                    <img
                      src={file.thumbnail}
                      alt={file.name}
                      className="w-20 h-15 object-cover rounded bg-black"
                      loading="lazy"
                    />
                  ) : (
                    <div className="w-20 h-15 flex items-center justify-center text-[28px] rounded bg-[#222235] text-gray-500">
                      {getFileIconLetter(file.ext)}
                    </div>
                  )}
                  <span
                    className="text-[11px] text-gray-400 text-center w-full overflow-hidden text-ellipsis whitespace-nowrap"
                    title={file.name}
                  >
                    {file.name}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* 底部按钮 */}
        <div className="flex justify-end gap-3 px-5 py-3.5 border-t border-[#333346]">
          <button
            className="px-5 py-2 rounded-md bg-[#333346] text-gray-300 text-[13px] font-medium hover:bg-[#444459] transition-colors"
            onClick={handleCancel}
          >
            取消
          </button>
          <button
            className="px-5 py-2 rounded-md bg-purple-600 text-white text-[13px] font-medium hover:bg-purple-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
            disabled={!selectedPath}
            onClick={handleConfirm}
          >
            确认
          </button>
        </div>
      </div>
    </div>
  )
}
